import { TrainingSession, Schedule } from "./types";

export const sampleSessions: TrainingSession[] = [
  {
    id: "sample-1",
    date: "2026-06-02",
    gym: "Alliance HQ",
    duration: 90,
    gi: true,
    intensity: 4,
    positions: ["Closed Guard", "Mount", "Back Control"],
    submissionsGiven: ["Triangle", "RNC"],
    submissionsReceived: ["Armbar"],
    sweepsGiven: [], sweepsReceived: [], escapesGiven: [], escapesReceived: [],
    notes: "Great drilling session. Worked on back takes from turtle.",
    whatWorked: "Hip escapes felt smooth. Triangle setup from closed guard was tight.",
    whatDidntWork: "Getting swept when trying to pass open guard.",
    focus: "Open guard passing next session",
  },
  {
    id: "sample-2",
    date: "2026-05-30",
    gym: "Alliance HQ",
    duration: 75,
    gi: false,
    intensity: 5,
    positions: ["Leg Entanglement", "Half Guard", "Back Control"],
    submissionsGiven: ["Heel Hook", "RNC"],
    submissionsReceived: ["Heel Hook", "Heel Hook"],
    sweepsGiven: [], sweepsReceived: [], escapesGiven: [], escapesReceived: [],
    notes: "Hard rolling. Got caught in heel hook twice, need to defend better.",
    whatWorked: "Back takes from body lock were consistent.",
    whatDidntWork: "Leg lock defense is a big hole in my game.",
    focus: "Leg lock defense fundamentals",
  },
  {
    id: "sample-3",
    date: "2026-05-27",
    gym: "10th Planet Local",
    duration: 60,
    gi: false,
    intensity: 3,
    positions: ["Closed Guard", "Open Guard"],
    submissionsGiven: ["Guillotine"],
    submissionsReceived: ["Armbar", "Triangle"],
    sweepsGiven: [], sweepsReceived: [], escapesGiven: [], escapesReceived: [],
    notes: "Technique class on rubber guard. Light rolling at end.",
    whatWorked: "Rubber guard entries feeling more natural.",
    whatDidntWork: "Losing posture when partner is strong.",
    focus: "Keep drilling rubber guard sequences",
  },
  {
    id: "sample-4",
    date: "2026-05-24",
    gym: "Alliance HQ",
    duration: 90,
    gi: true,
    intensity: 4,
    positions: ["Side Control", "Mount", "Closed Guard"],
    submissionsGiven: ["Kimura", "Armbar"],
    submissionsReceived: [],
    sweepsGiven: [], sweepsReceived: [], escapesGiven: [], escapesReceived: [],
    notes: "Gi fundamentals. Focused on pressure passing.",
    whatWorked: "Knee slice pass working well against flexible guards.",
    whatDidntWork: "Defending underhook from half guard bottom.",
    focus: "Half guard bottom recovery",
  },
  {
    id: "sample-5",
    date: "2026-05-20",
    gym: "Alliance HQ",
    duration: 120,
    gi: true,
    intensity: 5,
    positions: ["Back Control", "Mount", "Turtle"],
    submissionsGiven: ["RNC", "Triangle", "Kimura"],
    submissionsReceived: ["Kimura", "D'Arce"],
    sweepsGiven: [], sweepsReceived: [], escapesGiven: [], escapesReceived: [],
    notes: "Competition prep session. Hard rounds.",
    whatWorked: "Back retention when opponent tries to escape.",
    whatDidntWork: "Getting tired in round 4+. Conditioning needs work.",
    focus: "Cardio and competition mindset",
  },
];

export const sampleSchedules: Schedule[] = [
  {
    id: "sched-1",
    name: "Tuesday Evening No-Gi",
    dayOfWeek: 2,
    time: "18:00",
    duration: 90,
    gi: false,
    gym: "Alliance HQ",
    active: true, type: "recurring",
  },
  {
    id: "sched-2",
    name: "Thursday Gi Class",
    dayOfWeek: 4,
    time: "19:00",
    duration: 75,
    gi: true,
    gym: "Alliance HQ",
    active: true, type: "recurring",
  },
  {
    id: "sched-3",
    name: "Saturday Open Mat",
    dayOfWeek: 6,
    time: "10:00",
    duration: 120,
    gi: true,
    gym: "Alliance HQ",
    active: true, type: "recurring",
  },
];
